### ISSUE TITLE
Date ranging from 1 BS or 1000 BS?

### ISSUE THREAD

**Issue by sushiljic** [leapfrogtechnology/Nepali-Date-Picker#19]
I would like to manually input the data from 1BS or 1000 BS, it is possible?
I can provide the data and i would love to contribute too.

**Comment by sanishmaharjan** [comment]
@sushiljic Currently, it supports from 1970BS to 2100BS. And we do not have the ability to manually input the data. 
If you have data it would be great if you could contribute.

**Comment by mesaugat** [comment]
@sushiljic @sanishmaharjan Closing this issue as there has been no progress for quite a while. Re-open the thread if you want to revive the conversation.
