### ISSUE TITLE
Problem with datepicker position

### ISSUE THREAD

**Issue by ad1199** [leapfrogtechnology/Nepali-Date-Picker#2]
Datepicker doesn't appear at the position of datepicker input. The left and top value of datepicker css is incorrect.

**Comment by ad1199** [comment]
When I npm install the package, the nepaliDatePicker.js uses position() to get the left and top value but the file in github uses offset() to get those values.

**Comment by sanishmaharjan** [comment]
@ad1199  Because of I forget to upgrade version in npm, you get the different code from Github and npm install package. Now I have upgade version in npm. 

And thanks for the comment..:+1:

**Comment by ad1199** [comment]
Thank you! @sanishmaharjan
