### ISSUE TITLE
How to use this with npm? 

### ISSUE THREAD

**Issue by gwachhamit** [leapfrogtechnology/Nepali-Date-Picker#24]
I am trying to use this Nepali Date Picker in Vue js. And encountering the issue like 
![image](https://user-images.githubusercontent.com/11870771/76384033-d72be600-6385-11ea-9117-6f0262676673.png)
.

**Comment by mesaugat** [comment]
@gwachhamit You'll need jQuery to use Nepali-Date-Picker.

**Comment by gwachhamit** [comment]
Hey can I wrap your this nepali date picker package with vue js components, and publish? so that others developers can use in vue js.

**Comment by mesaugat** [comment]
Hello @gwachhamit, yes you can use this package and publish it as a Vue component but make sure you give proper attribution to Leapfrog Technology and/or Sanish Maharjan.

Take a look at the ISC license here 👉  https://github.com/leapfrogtechnology/nepali-date-picker/blob/master/LICENSE
