### ISSUE TITLE
Error: Property 'nepaliDatePicker' does not exist on type 'JQuery<HTMLElement>

### ISSUE THREAD

**Issue by Oliverq755** [leapfrogtechnology/nepali-date-picker#27]
Hey there, thanks for the datepicker, 

I tried to implement it in my application, however, its throwing error on Initialize Date Picker

ts file: 
```
$(".date-picker").nepaliDatePicker({
      dateFormat: "%D, %M %d, %y",
      closeOnDateSelect: true,
      minDate: "सोम, जेठ १०, २०७३",
      maxDate: "मंगल, जेठ ३२, २०७३"
    });

```

HTML:
```
<div class="form-group">
    <input type="text" value="" name="date" class="date-picker nepalidatepicker">
</div>
```

Do I need to import anything in my TS file to get rid of this error?

**Comment by NikeshNiraula** [comment]
Did you solve the issue? I am facing the same error. if yes please comment how.

**Comment by mesaugat** [comment]
Stale issue, closing.
