### ISSUE TITLE
Get date in AD on date change

### ISSUE THREAD

**Issue by ad1199** [leapfrogtechnology/Nepali-Date-Picker#3]
Is there a way we can get date in AD on date change and input date in AD on plugin initialization or during runtime?
What I'm trying to do is, get a date in AD when user changes the date in nepali and add the date in hidden input so that I don't have to convert it in backend.

**Comment by sanishmaharjan** [comment]
@ad1199  you can get AD date on change as following:
```
$(".bod-picker").on("dateChange", function (event) {
           console.log(event);
           var adDate = event.datePickerData.adDate;
           console.log(adDate);
        });
```
For more you can console log event.
