### ISSUE TITLE
Issue in today's date selection in calendar UI

### ISSUE THREAD

**Issue by rumus007** [leapfrogtechnology/nepali-date-picker#35]
Date selection for nepali date seems to be off by one day in the calendar UI. 
Issue seems to started from english date April 1st, 2021 (Chaitra 19th, 2077)

![date issue](https://user-images.githubusercontent.com/51116139/113964059-7998f000-984a-11eb-912b-70ab424f4482.png)

**Comment by mesaugat** [comment]
Stale issue, closing.
