### ISSUE TITLE
cant use year and month only

### ISSUE THREAD

**Issue by diwakar2000** [leapfrogtechnology/nepali-date-picker#40]
i got the following error while using month and year only:

jquery.nepaliDatePicker.min.js:1 Uncaught ReferenceError: Missing required parameters: bsYear, bsMonth, bsDate

am i doing something wrong??
following is my code:

    $(document).ready(function(){
        $('#nepaliDatepicker').nepaliDatePicker({
	        dateFormat: "%y-%m",
            closeOnDateSelect: true
	    });
	    let nep_date = (calendarFunctions.getBsDateByAdDate(year, month, day));
	    let nepMonth = calendarFunctions.getNepaliNumber(nep_date.bsMonth);
	    let nepYear = calendarFunctions.getNepaliNumber(nep_date.bsYear);
	    $('#nepaliDatepicker').val(nepYear+'-'+nepMonth);
    });

**Comment by bitcoinBandit1234** [comment]
It's too late now, but did you figure it out?

**Comment by mesaugat** [comment]
Stale issue, closing.
