### ISSUE TITLE
not clear, what to import in react

### ISSUE THREAD

**Issue by AsicsBajracharya** [leapfrogtechnology/nepali-date-picker#44]
documentation is not clear on what to import this in reactjs,

**Comment by mesaugat** [comment]
Hello @AsicsBajracharya this is a jQuery plugin thus it can't be used in React code directly as "React is unaware of changes made to the DOM outside of React". You might want to check https://reactjs.org/docs/integrating-with-other-libraries.html to  support your use case.

If you don't want to create your own React wrapper component around nepali-date-picker jQuery plugin, try some react based nepali datepicker libraries.
