### ISSUE TITLE
Date data wrong for 2081 jestha

### ISSUE THREAD

**Issue by gautam-saroj** [leapfrogtechnology/nepali-date-picker#57]
In the month of jesth of 2081 there should be total 32 days in that month but there is only 31 days in your data set. Please fix this issue.

**Comment by aaajjan** [comment]
@sanishmaharjan  , today i got the issue in date conversion from english to nepali. 
From Application Result is: 2024/4/2 to 2081/12/19  
should be 2024/4/2 to 2081/12/20 have you fix this issue or not?

**Comment by sanjaykpoudel** [comment]
today i got the issue in date conversion from english to nepali.
From Application Result is: 2024/4/2 to 2081/12/19
should be 2024/4/2 to 2081/12/20 have you fix this issue or not?

**Comment by sanjaykpoudel** [comment]
In the month of jesth of 2081 there should be total 32 days in that month but there is only 31 days in your data set. Please fix this issue. I would be great full for your help

**Comment by Bijen-M** [comment]
> In the month of jesth of 2081 there should be total 32 days in that month but there is only 31 days in your data set. Please fix this issue.

same issue. is there any update on this?

**Comment by sanjaykpoudel** [comment]
> > In the month of jesth of 2081 there should be total 32 days in that month but there is only 31 days in your data set. Please fix this issue.
> 
> same issue. is there any update on this?

no still the problem exist and i have sent the email too but no reply 
if its not solved then need to look for another alternative.
if you get any thing then please let me know

**Comment by sanjaykpoudel** [comment]
> these guys are too lazy to give answer or fixes. here is the code from their site, i had tried and good to know that it worked as charm.
> 
> https://leapfrogtechnology.github.io/nepali-date-picker/src/nepaliDatePicker.js
> 
> Note: there are few methods missing at new one. Please copy those methods from old js to new

thank you it worked. 
can you please tell me what you have changed ? function or data ? (just for future)
thank you in advance

**Comment by mesaugat** [comment]
The new version v2.0.2 should fix the wrong dates. https://github.com/leapfrogtechnology/nepali-date-picker/releases/tag/2.0.2

Download the latest version from https://github.com/leapfrogtechnology/nepali-date-picker/blob/2.0.2/dist/nepaliDatePicker.min.js

Instead of using the `leapfrogtechnology.github.io` domain use the `unpkg` URL for better caching and speed. https://unpkg.com/nepali-date-picker@2.0.2/dist/nepaliDatePicker.min.js
